
class TimeConstant:
    """Class containing basic time utilities"""
    WEEKS_PER_MONTH = 4
    DAYS_PER_WEEK = 7
    HOURS_PER_DAY = 24
    MINUTES_PER_HOUR = 60
    SECONDS_PER_MINUTE = 60
    SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR
    SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY
    SECONDS_PER_WEEK = SECONDS_PER_DAY * DAYS_PER_WEEK
    SECONDS_PER_MONTH = SECONDS_PER_WEEK * WEEKS_PER_MONTH